version: 1.2.{build}
image: Visual Studio 2019
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: fi6bOacZqdXXRAE679Iu7mXAvdr8owltFkXYajL6TonDcYhL6mXitW2gyMkW8UDf
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore
build_script:
- cmd: dotnet build
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
  project: ReadOnlyDictionary.sln
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+
  on:
    branch: master
